var N = null;var sourcesIndex = {};
sourcesIndex["matches"] = {"name":"","files":["lib.rs"]};
sourcesIndex["mini_haskell"] = {"name":"","dirs":[{"name":"scanner","files":["basic.rs","char_string.rs","identifier.rs","layout.rs","numeric.rs","special.rs","whitespace.rs"]},{"name":"utils","files":["char.rs","control.rs","iter.rs","logging.rs","misc.rs"]}],"files":["error.rs","input.rs","lexeme.rs","lib.rs","rc_view.rs","scanner.rs","utils.rs"]};
sourcesIndex["num_bigint"] = {"name":"","files":["algorithms.rs","bigint.rs","biguint.rs","lib.rs","macros.rs","monty.rs"]};
sourcesIndex["num_integer"] = {"name":"","files":["average.rs","lib.rs","roots.rs"]};
sourcesIndex["num_traits"] = {"name":"","dirs":[{"name":"ops","files":["checked.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]}],"files":["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]};
sourcesIndex["unic_char_property"] = {"name":"","files":["lib.rs","macros.rs","pkg_info.rs","property.rs","range_types.rs","tables.rs"]};
sourcesIndex["unic_char_range"] = {"name":"","files":["iter.rs","iter_fused.rs","lib.rs","macros.rs","pkg_info.rs","range.rs","step.rs"]};
sourcesIndex["unic_common"] = {"name":"","files":["lib.rs","pkg_info.rs","version.rs"]};
sourcesIndex["unic_ucd_category"] = {"name":"","files":["category.rs","lib.rs","pkg_info.rs"]};
sourcesIndex["unic_ucd_version"] = {"name":"","files":["lib.rs","pkg_info.rs","unicode_version.rs"]};
createSourceSidebar();
