// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate.exe property-values ucd --include gc
//
// Unicode version: 13.0.0.
//
// ucd-generate 0.2.9 is available on crates.io.

pub const PROPERTY_VALUES: &'static [(&'static str, &'static [(&'static str, &'static str)])] = &[
  ("General_Category", &[("c", "Other"), ("casedletter", "Cased_Letter"),
  ("cc", "Control"), ("cf", "Format"),
  ("closepunctuation", "Close_Punctuation"), ("cn", "Unassigned"),
  ("cntrl", "Control"), ("co", "Private_Use"), ("combiningmark", "Mark"),
  ("connectorpunctuation", "Connector_Punctuation"), ("control", "Control"),
  ("cs", "Surrogate"), ("currencysymbol", "Currency_Symbol"),
  ("dashpunctuation", "Dash_Punctuation"),
  ("decimalnumber", "Decimal_Number"), ("digit", "Decimal_Number"),
  ("enclosingmark", "Enclosing_Mark"),
  ("finalpunctuation", "Final_Punctuation"), ("format", "Format"),
  ("initialpunctuation", "Initial_Punctuation"), ("l", "Letter"),
  ("lc", "Cased_Letter"), ("letter", "Letter"),
  ("letternumber", "Letter_Number"), ("lineseparator", "Line_Separator"),
  ("ll", "Lowercase_Letter"), ("lm", "Modifier_Letter"),
  ("lo", "Other_Letter"), ("lowercaseletter", "Lowercase_Letter"),
  ("lt", "Titlecase_Letter"), ("lu", "Uppercase_Letter"), ("m", "Mark"),
  ("mark", "Mark"), ("mathsymbol", "Math_Symbol"), ("mc", "Spacing_Mark"),
  ("me", "Enclosing_Mark"), ("mn", "Nonspacing_Mark"),
  ("modifierletter", "Modifier_Letter"),
  ("modifiersymbol", "Modifier_Symbol"), ("n", "Number"),
  ("nd", "Decimal_Number"), ("nl", "Letter_Number"), ("no", "Other_Number"),
  ("nonspacingmark", "Nonspacing_Mark"), ("number", "Number"),
  ("openpunctuation", "Open_Punctuation"), ("other", "Other"),
  ("otherletter", "Other_Letter"), ("othernumber", "Other_Number"),
  ("otherpunctuation", "Other_Punctuation"), ("othersymbol", "Other_Symbol"),
  ("p", "Punctuation"), ("paragraphseparator", "Paragraph_Separator"),
  ("pc", "Connector_Punctuation"), ("pd", "Dash_Punctuation"),
  ("pe", "Close_Punctuation"), ("pf", "Final_Punctuation"),
  ("pi", "Initial_Punctuation"), ("po", "Other_Punctuation"),
  ("privateuse", "Private_Use"), ("ps", "Open_Punctuation"),
  ("punct", "Punctuation"), ("punctuation", "Punctuation"), ("s", "Symbol"),
  ("sc", "Currency_Symbol"), ("separator", "Separator"),
  ("sk", "Modifier_Symbol"), ("sm", "Math_Symbol"), ("so", "Other_Symbol"),
  ("spaceseparator", "Space_Separator"), ("spacingmark", "Spacing_Mark"),
  ("surrogate", "Surrogate"), ("symbol", "Symbol"),
  ("titlecaseletter", "Titlecase_Letter"), ("unassigned", "Unassigned"),
  ("uppercaseletter", "Uppercase_Letter"), ("z", "Separator"),
  ("zl", "Line_Separator"), ("zp", "Paragraph_Separator"),
  ("zs", "Space_Separator"), ]),
];
