name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DOC_PATH: target/doc

jobs:
  build:
    name: ${{ matrix.readable_os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          readable_os: Ubuntu
        - os: windows-latest
          readable_os: Windows
        - os: macos-latest
          readable_os: macOS
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy checks
      run: cargo clippy -- -D warnings
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Generate Documentation
      run: |
        cargo doc
        cp .github/pages/index.html ${{ env.DOC_PATH }}
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
